#!/bin/bash

#SBATCH --job-name=rad
#SBATCH -t 01:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=16
#SBATCH --cpus-per-task=1
#SBATCH --mail-type=ALL

K_MIN=0 \
K_MAX=47 \
J_INDICES=48,15 \
I_INDICES=16,0,48,96 \
N_PARALLEL=8 \
TASK_COUNT=0 \
bash looper.sh
