#!/bin/bash

#SBATCH --job-name=2_M
#SBATCH --output=isca.out
#SBATCH --error=isca.err
#SBATCH -t 120:00:00
#SBATCH -A naiss2025-1-5 
#SBATCH -n 32
#SBATCH -c 1
#SBATCH --mail-type=ALL

export OMP_NUM_THREADS=1

bash run_ne_dayside_chunks.sh 
